/**
 * Regenerates `src/data/slices.generated.ts` from the contents of
 * `src/data/research/`. Run via `npm run gen` — and it runs automatically
 * before `dev`, `build` and `validate`, so **adding a research slice is now
 * just dropping the JSON file in the folder.** No import line, no array entry.
 *
 * Replaces the hand-maintained 100+ line import list in `src/data/index.ts`
 * (2026-08-12, Thomas: "yes, do it"). Deliberately a codegen script rather
 * than Vite's `import.meta.glob`, which looks cleaner but is a Vite-only API —
 * `npm run validate` executes the data layer under tsx/Node, where glob does
 * not exist, and a loader that works in the app but breaks the validator
 * would be worse than the boilerplate it replaced.
 *
 * Slices are emitted in sorted filename order. That is safe where the old
 * hand-ordering was load-bearing: duplicate report ids and duplicate edges
 * both FAIL `npm run validate` outright now, so no data can silently depend
 * on which copy loads first — and the seed set stays explicitly first in
 * index.ts regardless.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const researchDir = join(here, '..', 'src', 'data', 'research')
const outPath = join(here, '..', 'src', 'data', 'slices.generated.ts')

/**
 * On-disk research files deliberately NOT loaded into the corpus.
 *
 * Found 2026-08-12 during the loader rework: these ten sat in the folder but
 * were absent from the old hand-written import list — four of them entire
 * researched countries (BF, TG, GA, TD, the AF G.11/G.12 WAEMU/CEMAC batches)
 * whose palette entries exist while their reports never load. Whether that
 * was ever deliberate is not recorded anywhere. Listed here EXPLICITLY so the
 * new auto-loader reproduces the exact corpus the old list produced, until
 * Thomas rules on wiring them (round-3 review doc, Q10). To wire one: delete
 * its line here and run `npm run validate`.
 */
const UNWIRED = new Set<string>([
  // Emptied 2026-08-12 — Thomas's Q10 answer to wiring the ten lost slices: "Of course".
  // The mechanism stays for any future deliberate exclusion.
])

const files = readdirSync(researchDir).filter((f) => f.endsWith('.json')).sort()
const wired = files.filter((f) => !UNWIRED.has(f))
const skipped = files.filter((f) => UNWIRED.has(f))
const missingExclusions = [...UNWIRED].filter((f) => !files.includes(f))

const ident = (f: string, i: number) => `s${i}_${f.replace(/\.json$/, '').replace(/[^a-zA-Z0-9]/g, '_')}`

const lines: string[] = []
lines.push('// AUTO-GENERATED by scripts/gen-slices.ts — do not edit by hand.')
lines.push('// Regenerate with `npm run gen` (runs automatically before dev/build/validate).')
lines.push('// To add a research slice: drop the JSON in src/data/research/ — that is all.')
lines.push('// To exclude one: add it to UNWIRED in scripts/gen-slices.ts.')
wired.forEach((f, i) => lines.push(`import ${ident(f, i)} from './research/${f}'`))
lines.push('')
lines.push('/** Every wired research slice, sorted by filename. Cast by the loader. */')
lines.push('export const sliceModules: unknown[] = [')
wired.forEach((f, i) => lines.push(`  ${ident(f, i)},`))
lines.push(']')
lines.push('')

const next = lines.join('\n')
const prev = existsSync(outPath) ? readFileSync(outPath, 'utf8') : ''
if (prev !== next) {
  writeFileSync(outPath, next)
  console.log(`gen-slices: wrote ${wired.length} slices to slices.generated.ts (${skipped.length} unwired by rule)`)
} else {
  console.log(`gen-slices: up to date — ${wired.length} slices (${skipped.length} unwired by rule)`)
}
if (missingExclusions.length) {
  console.warn(`gen-slices: UNWIRED names ${missingExclusions.length} file(s) that no longer exist: ${missingExclusions.join(', ')} — prune the list`)
}
